title: "Real World Coq"

url: https://ejgallego.github.io
baseurl: /real-world-coq
repository: ejgallego/real-world-coq

# permalink: date

theme: minima
markdown: kramdown

header_pages:
  - 2023-09-bu/index.md

kramdown:
  input: GFM
#   syntax_highlighter: rouge
#   auto_ids:       true
#   toc_levels:     1..3
