title: "Sabanci Coq Course"

url: https://ejgallego.github.io
baseurl: /real-world-coq

# permalink: date

theme: minima
markdown: kramdown

kramdown:
  input: GFM
#   syntax_highlighter: rouge
#   auto_ids:       true
#   toc_levels:     1..3
